# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'add_repostaje.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QHBoxLayout, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QVBoxLayout,
    QWidget)

class Ui_AddRepostajeView(object):
    def setupUi(self, AddRepostajeView):
        if not AddRepostajeView.objectName():
            AddRepostajeView.setObjectName(u"AddRepostajeView")
        AddRepostajeView.resize(420, 420)
        AddRepostajeView.setStyleSheet(u"QWidget {\n"
"    background-color: #081c20;\n"
"}\n"
"QWidget {\n"
"    background-color: #081c20;\n"
"}\n"
"/* ===============================\n"
"   MENSAJES DIN\u00c1MICOS\n"
"=============================== */\n"
"\n"
"QLabel#mensajeError {\n"
"    color: #fbbf24;   /* \u00e1mbar */\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QLabel#mensajeInfo {\n"
"    color: #38bdf8;   /* azul */\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLabel#mensajeOk {\n"
"    color: #4ade80;   /* verde suave */\n"
"    font-size: 13px;\n"
"}\n"
"")
        self.vboxLayout = QVBoxLayout(AddRepostajeView)
        self.vboxLayout.setObjectName(u"vboxLayout")
        self.labelTitulo = QLabel(AddRepostajeView)
        self.labelTitulo.setObjectName(u"labelTitulo")
        font = QFont()
        font.setBold(True)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setStyleSheet(u"/* =========================================\n"
"   LABELS \u2013 AZUL PETR\u00d3LEO OSCURO\n"
"========================================= */\n"
"\n"
"/* Label normal (texto est\u00e1ndar) */\n"
"QLabel {\n"
"    color: #cfe9ee;              /* azul muy claro */\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"/* T\u00edtulos de secci\u00f3n / pantallas */\n"
"QLabel#titulo {\n"
"    color: #22d3ee;              /* cyan petr\u00f3leo */\n"
"    font-size: 22px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* Subt\u00edtulos */\n"
"QLabel#subtitulo {\n"
"    color: #7dd3fc;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"/* Labels de formulario (Usuario, Contrase\u00f1a, etc.) */\n"
"QLabel#campo {\n"
"    color: #9ddae6;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"/* Texto secundario / ayuda */\n"
"QLabel#hint {\n"
"    color: #6fbdd0;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* Avisos / combustible / warning */\n"
"QLabel#warning {\n"
"    color: #fbbf24;              /* \u00e1mbar */"
                        "\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* Error */\n"
"QLabel#error {\n"
"    color: #fb7185;              /* rojo suave */\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"/* =========================================\n"
"   MENSAJES DE ERROR \u2013 ESTILO PROPIO\n"
"========================================= */\n"
"\n"
"QLabel#error {\n"
"    color: #fbbf24;          /* \u00e1mbar visible */\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"")
        self.labelTitulo.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.vboxLayout.addWidget(self.labelTitulo)

        self.inputFecha = QDateEdit(AddRepostajeView)
        self.inputFecha.setObjectName(u"inputFecha")
        self.inputFecha.setStyleSheet(u"/* =========================================\n"
"   DATE EDIT \u2013 SIN DESCUADRES (FINAL)\n"
"========================================= */\n"
"\n"
"QDateEdit {\n"
"    background-color: #0f3a43;\n"
"    color: #ecfeff;\n"
"\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 12px;\n"
"\n"
"    padding-left: 12px;\n"
"    padding-right: 30px;\n"
"\n"
"    font-size: 14px;\n"
"    min-height: 34px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QDateEdit:hover {\n"
"    border: 1px solid #22d3ee;\n"
"}\n"
"\n"
"/* Focus (MISMO BORDE \u2192 NO DESCUADRA) */\n"
"QDateEdit:focus {\n"
"    background-color: #155e6a;\n"
"    border: 1px solid #22d3ee;\n"
"}\n"
"\n"
"/* Texto interno */\n"
"QDateEdit QAbstractSpinBox {\n"
"    background: transparent;\n"
"    color: #ecfeff;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"/* Bot\u00f3n calendario */\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: content;\n"
"    subcontrol-position: right center;\n"
"\n"
"    width: 28px;\n"
"    border-left: 1px solid #1f6f7a;\n"
""
                        "    margin: 0;\n"
"    padding: 0;\n"
"}\n"
"\n"
"/* Sin icono */\n"
"QDateEdit::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* =========================================\n"
"   CALENDARIO \u2013 AZUL PETR\u00d3LEO (CUERPO)\n"
"========================================= */\n"
"\n"
"QCalendarWidget {\n"
"    background-color: #123b44;\n"
"    color: #ecfeff;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Barra superior (mes / a\u00f1o) */\n"
"QCalendarWidget QWidget {\n"
"    background-color: #155e6a;\n"
"}\n"
"\n"
"/* Botones navegaci\u00f3n */\n"
"QCalendarWidget QToolButton {\n"
"    background-color: #0f3a43;\n"
"    color: #ecfeff;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 2px 6px;\n"
"    margin: 2px;\n"
"\n"
"    min-width: 20px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton:hover {\n"
"    background-color: #155e6a;\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* Combo mes / a\u00f1o */\n"
""
                        "QCalendarWidget QComboBox {\n"
"    background-color: #0f3a43;\n"
"    color: #ecfeff;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 6px;\n"
"\n"
"    padding: 2px 6px;\n"
"    min-height: 22px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"\n"
"\n"
"/* =========================================\n"
"   CALENDARIO \u2013 CUERPO DE D\u00cdAS\n"
"========================================= */\n"
"\n"
"QCalendarWidget QAbstractItemView {\n"
"    background-color: #123b44;\n"
"    color: #d9f5f8;\n"
"\n"
"    selection-background-color: #22d3ee;\n"
"    selection-color: #041518;\n"
"\n"
"    font-size: 11px;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Celdas */\n"
"QCalendarWidget QAbstractItemView::item {\n"
"    padding: 3px;\n"
"}\n"
"\n"
"/* Hover d\u00eda */\n"
"QCalendarWidget QAbstractItemView::item:hover {\n"
"    background-color: #155e6a;\n"
"}\n"
"\n"
"/* D\u00eda seleccionado */\n"
"QCalendarWidget QAbstractItemView::item:selected {\n"
"    background-color: #22d3ee;\n"
"    color: #041518;\n"
"    bord"
                        "er-radius: 4px;\n"
"}\n"
"\n"
"/* Fines de semana */\n"
"QCalendarWidget QAbstractItemView::item:!enabled {\n"
"    color: #fb7185;\n"
"}\n"
"\n"
"\n"
"\n"
"/* =========================================\n"
"   CALENDARIO \u2013 CABECERAS\n"
"========================================= */\n"
"\n"
"/* Cabecera superior (lu ma mi...) */\n"
"QCalendarWidget QHeaderView::section {\n"
"    background-color: #155e6a;\n"
"    color: #7dd3fc;\n"
"    padding: 3px;\n"
"    border: none;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"/* \ud83d\udd11 BARRA LATERAL IZQUIERDA (NEGRA) */\n"
"QCalendarWidget QHeaderView::section:vertical {\n"
"    background-color: #020617;   /* negro elegante */\n"
"    color: #7dd3fc;\n"
"    border: none;\n"
"    padding: 4px;\n"
"    font-size: 11px;\n"
"}\n"
"/* =========================================\n"
"   CAMPOS DESHABILITADOS\n"
"========================================= */\n"
"\n"
"QLineEdit:disabled,\n"
"QDateEdit:disabled {\n"
"    background-color: #0b2a30;   /* m\u00e1s oscuro */\n"
"  "
                        "  color: #6fbdd0;              /* texto apagado */\n"
"    border: 1px solid #0e3a40;\n"
"}")
        self.inputFecha.setCalendarPopup(True)

        self.vboxLayout.addWidget(self.inputFecha)

        self.inputLitros = QLineEdit(AddRepostajeView)
        self.inputLitros.setObjectName(u"inputLitros")
        self.inputLitros.setStyleSheet(u"/* =========================================\n"
"   ENTRADAS DE TEXTO \u2013 CONTRASTE AZUL PETR\u00d3LEO\n"
"========================================= */\n"
"\n"
"QLineEdit {\n"
"    background-color: #0f3a43;        /* M\u00c1S CLARO que el fondo */\n"
"    color: #ecfeff;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 12px;\n"
"    padding: 11px 16px;\n"
"    font-size: 14px;\n"
"    selection-background-color: #22d3ee;\n"
"    selection-color: #041518;\n"
"}\n"
"\n"
"/* Placeholder */\n"
"QLineEdit::placeholder {\n"
"    color: #9adce6;\n"
"}\n"
"\n"
"/* Hover */\n"
"QLineEdit:hover {\n"
"    border-color: #22d3ee;\n"
"    background-color: #134852;\n"
"}\n"
"\n"
"/* Focus: contraste fuerte pero elegante */\n"
"QLineEdit:focus {\n"
"    background-color: #155e6a;\n"
"    border: 2px solid #22d3ee;\n"
"}\n"
"/* =========================================\n"
"   CAMPOS DESHABILITADOS\n"
"========================================= */\n"
"\n"
"QLineEdit:disabled,\n"
"QDateEdit:disabled {\n"
"    backgr"
                        "ound-color: #0b2a30;   /* m\u00e1s oscuro */\n"
"    color: #6fbdd0;              /* texto apagado */\n"
"    border: 1px solid #0e3a40;\n"
"}")

        self.vboxLayout.addWidget(self.inputLitros)

        self.inputPrecio = QLineEdit(AddRepostajeView)
        self.inputPrecio.setObjectName(u"inputPrecio")
        self.inputPrecio.setStyleSheet(u"/* =========================================\n"
"   ENTRADAS DE TEXTO \u2013 CONTRASTE AZUL PETR\u00d3LEO\n"
"========================================= */\n"
"\n"
"QLineEdit {\n"
"    background-color: #0f3a43;        /* M\u00c1S CLARO que el fondo */\n"
"    color: #ecfeff;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 12px;\n"
"    padding: 11px 16px;\n"
"    font-size: 14px;\n"
"    selection-background-color: #22d3ee;\n"
"    selection-color: #041518;\n"
"}\n"
"\n"
"/* Placeholder */\n"
"QLineEdit::placeholder {\n"
"    color: #9adce6;\n"
"}\n"
"\n"
"/* Hover */\n"
"QLineEdit:hover {\n"
"    border-color: #22d3ee;\n"
"    background-color: #134852;\n"
"}\n"
"\n"
"/* Focus: contraste fuerte pero elegante */\n"
"QLineEdit:focus {\n"
"    background-color: #155e6a;\n"
"    border: 2px solid #22d3ee;\n"
"}\n"
"/* =========================================\n"
"   CAMPOS DESHABILITADOS\n"
"========================================= */\n"
"\n"
"QLineEdit:disabled,\n"
"QDateEdit:disabled {\n"
"    backgr"
                        "ound-color: #0b2a30;   /* m\u00e1s oscuro */\n"
"    color: #6fbdd0;              /* texto apagado */\n"
"    border: 1px solid #0e3a40;\n"
"}")

        self.vboxLayout.addWidget(self.inputPrecio)

        self.inputKilometros = QLineEdit(AddRepostajeView)
        self.inputKilometros.setObjectName(u"inputKilometros")
        self.inputKilometros.setStyleSheet(u"/* =========================================\n"
"   ENTRADAS DE TEXTO \u2013 CONTRASTE AZUL PETR\u00d3LEO\n"
"========================================= */\n"
"\n"
"QLineEdit {\n"
"    background-color: #0f3a43;        /* M\u00c1S CLARO que el fondo */\n"
"    color: #ecfeff;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 12px;\n"
"    padding: 11px 16px;\n"
"    font-size: 14px;\n"
"    selection-background-color: #22d3ee;\n"
"    selection-color: #041518;\n"
"}\n"
"\n"
"/* Placeholder */\n"
"QLineEdit::placeholder {\n"
"    color: #9adce6;\n"
"}\n"
"\n"
"/* Hover */\n"
"QLineEdit:hover {\n"
"    border-color: #22d3ee;\n"
"    background-color: #134852;\n"
"}\n"
"\n"
"/* Focus: contraste fuerte pero elegante */\n"
"QLineEdit:focus {\n"
"    background-color: #155e6a;\n"
"    border: 2px solid #22d3ee;\n"
"}\n"
"/* =========================================\n"
"   CAMPOS DESHABILITADOS\n"
"========================================= */\n"
"\n"
"QLineEdit:disabled,\n"
"QDateEdit:disabled {\n"
"    backgr"
                        "ound-color: #0b2a30;   /* m\u00e1s oscuro */\n"
"    color: #6fbdd0;              /* texto apagado */\n"
"    border: 1px solid #0e3a40;\n"
"}")

        self.vboxLayout.addWidget(self.inputKilometros)

        self.labelMensaje = QLabel(AddRepostajeView)
        self.labelMensaje.setObjectName(u"labelMensaje")
        self.labelMensaje.setVisible(False)
        self.labelMensaje.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.vboxLayout.addWidget(self.labelMensaje)

        self.hboxLayout = QHBoxLayout()
        self.hboxLayout.setObjectName(u"hboxLayout")
        self.btnSave = QPushButton(AddRepostajeView)
        self.btnSave.setObjectName(u"btnSave")
        self.btnSave.setStyleSheet(u"/* =========================================\n"
"   BOT\u00d3N ALTERNATIVO \u2013 BLANCO AZULADO\n"
"========================================= */\n"
"\n"
"QPushButton {\n"
"    background-color: #f1f5f9;      /* blanco azulado suave */\n"
"    color: #0f3a43;                 /* azul petr\u00f3leo oscuro */\n"
"\n"
"    border: 1px solid #22d3ee;\n"
"    border-radius: 12px;\n"
"\n"
"    padding: 10px 18px;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* Hover */\n"
"QPushButton:hover {\n"
"    background-color: #e0f2fe;      /* azul muy claro */\n"
"    color: #0b2a30;\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* Presionado */\n"
"QPushButton:pressed {\n"
"    background-color: #bae6fd;\n"
"    border-color: #06b6d4;\n"
"}\n"
"\n"
"/* Desactivado */\n"
"QPushButton:disabled {\n"
"    background-color: #e5e7eb;\n"
"    color: #64748b;\n"
"    border-color: #94a3b8;\n"
"}\n"
"")

        self.hboxLayout.addWidget(self.btnSave)

        self.btnCancel = QPushButton(AddRepostajeView)
        self.btnCancel.setObjectName(u"btnCancel")
        self.btnCancel.setStyleSheet(u"/* =========================================\n"
"   BOT\u00d3N ALTERNATIVO \u2013 BLANCO AZULADO\n"
"========================================= */\n"
"\n"
"QPushButton {\n"
"    background-color: #f1f5f9;      /* blanco azulado suave */\n"
"    color: #0f3a43;                 /* azul petr\u00f3leo oscuro */\n"
"\n"
"    border: 1px solid #22d3ee;\n"
"    border-radius: 12px;\n"
"\n"
"    padding: 10px 18px;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* Hover */\n"
"QPushButton:hover {\n"
"    background-color: #e0f2fe;      /* azul muy claro */\n"
"    color: #0b2a30;\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* Presionado */\n"
"QPushButton:pressed {\n"
"    background-color: #bae6fd;\n"
"    border-color: #06b6d4;\n"
"}\n"
"\n"
"/* Desactivado */\n"
"QPushButton:disabled {\n"
"    background-color: #e5e7eb;\n"
"    color: #64748b;\n"
"    border-color: #94a3b8;\n"
"}\n"
"")

        self.hboxLayout.addWidget(self.btnCancel)


        self.vboxLayout.addLayout(self.hboxLayout)


        self.retranslateUi(AddRepostajeView)

        QMetaObject.connectSlotsByName(AddRepostajeView)
    # setupUi

    def retranslateUi(self, AddRepostajeView):
        AddRepostajeView.setWindowTitle(QCoreApplication.translate("AddRepostajeView", u"A\u00f1adir repostaje", None))
        self.labelTitulo.setText(QCoreApplication.translate("AddRepostajeView", u"A\u00f1adir repostaje", None))
        self.inputLitros.setPlaceholderText(QCoreApplication.translate("AddRepostajeView", u"Litros", None))
        self.inputPrecio.setPlaceholderText(QCoreApplication.translate("AddRepostajeView", u"Precio total (\u20ac)", None))
        self.inputKilometros.setPlaceholderText(QCoreApplication.translate("AddRepostajeView", u"Kil\u00f3metros", None))
        self.btnSave.setText(QCoreApplication.translate("AddRepostajeView", u"Guardar", None))
        self.btnCancel.setText(QCoreApplication.translate("AddRepostajeView", u"Cancelar", None))
    # retranslateUi

