# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ajustes.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QHBoxLayout,
    QLabel, QPushButton, QSizePolicy, QSpinBox,
    QVBoxLayout, QWidget)

class Ui_AjustesView(object):
    def setupUi(self, AjustesView):
        if not AjustesView.objectName():
            AjustesView.setObjectName(u"AjustesView")
        AjustesView.resize(520, 521)
        AjustesView.setStyleSheet(u"QWidget {\n"
"    background-color: #081c20;\n"
"}\n"
"/* ===============================\n"
"   MENSAJES DIN\u00c1MICOS\n"
"=============================== */\n"
"\n"
"QLabel#mensajeError {\n"
"    color: #fbbf24;   /* \u00e1mbar */\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QLabel#mensajeInfo {\n"
"    color: #38bdf8;   /* azul */\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLabel#mensajeOk {\n"
"    color: #4ade80;   /* verde suave */\n"
"    font-size: 13px;\n"
"}\n"
"")
        self.vboxLayout = QVBoxLayout(AjustesView)
        self.vboxLayout.setObjectName(u"vboxLayout")
        self.labelTitulo = QLabel(AjustesView)
        self.labelTitulo.setObjectName(u"labelTitulo")
        font = QFont()
        font.setBold(True)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setStyleSheet(u"/* =========================================\n"
"   LABELS \u2013 AZUL PETR\u00d3LEO OSCURO\n"
"========================================= */\n"
"\n"
"/* Label normal (texto est\u00e1ndar) */\n"
"QLabel {\n"
"    color: #cfe9ee;              /* azul muy claro */\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"/* T\u00edtulos de secci\u00f3n / pantallas */\n"
"QLabel#titulo {\n"
"    color: #22d3ee;              /* cyan petr\u00f3leo */\n"
"    font-size: 22px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* Subt\u00edtulos */\n"
"QLabel#subtitulo {\n"
"    color: #7dd3fc;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"/* Labels de formulario (Usuario, Contrase\u00f1a, etc.) */\n"
"QLabel#campo {\n"
"    color: #9ddae6;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"/* Texto secundario / ayuda */\n"
"QLabel#hint {\n"
"    color: #6fbdd0;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* Avisos / combustible / warning */\n"
"QLabel#warning {\n"
"    color: #fbbf24;              /* \u00e1mbar */"
                        "\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* Error */\n"
"QLabel#error {\n"
"    color: #fb7185;              /* rojo suave */\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"/* =========================================\n"
"   MENSAJES DE ERROR \u2013 ESTILO PROPIO\n"
"========================================= */\n"
"\n"
"QLabel#error {\n"
"    color: #fbbf24;          /* \u00e1mbar visible */\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"")
        self.labelTitulo.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.vboxLayout.addWidget(self.labelTitulo)

        self.comboUnidadConsumo = QComboBox(AjustesView)
        self.comboUnidadConsumo.addItem("")
        self.comboUnidadConsumo.addItem("")
        self.comboUnidadConsumo.setObjectName(u"comboUnidadConsumo")
        self.comboUnidadConsumo.setStyleSheet(u"QComboBox {\n"
"    background-color: #0f3a43;\n"
"    color: #ecfeff;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 12px;\n"
"\n"
"    padding: 2px 8px;          /* \u2b05\ufe0f 1px menos */\n"
"    padding-right: 32px;\n"
"\n"
"    font-size: 12px;\n"
"    min-height: 34px;           /* \u2b05\ufe0f antes 38 */\n"
"}\n"
"\n"
"/* =========================================\n"
"   COMBOBOX \u2013 DESPLEGABLE AJUSTADO A ESTE TAMA\u00d1O\n"
"========================================= */\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: content;\n"
"    subcontrol-position: right center;\n"
"    width: 28px;\n"
"    border-left: 1px solid #1f6f7a;\n"
"}\n"
"\n"
"/* Quitamos la flecha por est\u00e9tica */\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"/* Lista desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #0b2a30;\n"
"    color: #cfe9ee;\n"
"\n"
"    border: 1px solid #155e75;\n"
"    border-radius: 8px;\n"
"\n"
"    max-height: 110px;          /* \ud83d"
                        "\udd11 CLAVE */\n"
"    padding: 2px;\n"
"\n"
"    selection-background-color: #22d3ee;\n"
"    selection-color: #041518;\n"
"\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Items */\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 2px 8px;           /* compacto */\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #155e6a;\n"
"    color: #ecfeff;\n"
"}\n"
"\n"
"/* Seleccionado */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #22d3ee;\n"
"    color: #041518;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    background-color: #155e6a;\n"
"    border: 1px solid #22d3ee;   /* MISMO GROSOR */\n"
"}")

        self.vboxLayout.addWidget(self.comboUnidadConsumo)

        self.comboFormatoPrecio = QComboBox(AjustesView)
        self.comboFormatoPrecio.addItem("")
        self.comboFormatoPrecio.addItem("")
        self.comboFormatoPrecio.setObjectName(u"comboFormatoPrecio")
        self.comboFormatoPrecio.setStyleSheet(u"QComboBox {\n"
"    background-color: #0f3a43;\n"
"    color: #ecfeff;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 12px;\n"
"\n"
"    padding: 2px 8px;          /* \u2b05\ufe0f 1px menos */\n"
"    padding-right: 32px;\n"
"\n"
"    font-size: 12px;\n"
"    min-height: 34px;           /* \u2b05\ufe0f antes 38 */\n"
"}\n"
"\n"
"/* =========================================\n"
"   COMBOBOX \u2013 DESPLEGABLE AJUSTADO A ESTE TAMA\u00d1O\n"
"========================================= */\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: content;\n"
"    subcontrol-position: right center;\n"
"    width: 28px;\n"
"    border-left: 1px solid #1f6f7a;\n"
"}\n"
"\n"
"/* Quitamos la flecha por est\u00e9tica */\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"/* Lista desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #0b2a30;\n"
"    color: #cfe9ee;\n"
"\n"
"    border: 1px solid #155e75;\n"
"    border-radius: 8px;\n"
"\n"
"    max-height: 110px;          /* \ud83d"
                        "\udd11 CLAVE */\n"
"    padding: 2px;\n"
"\n"
"    selection-background-color: #22d3ee;\n"
"    selection-color: #041518;\n"
"\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Items */\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 2px 8px;           /* compacto */\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #155e6a;\n"
"    color: #ecfeff;\n"
"}\n"
"\n"
"/* Seleccionado */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #22d3ee;\n"
"    color: #041518;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    background-color: #155e6a;\n"
"    border: 1px solid #22d3ee;   /* MISMO GROSOR */\n"
"}")

        self.vboxLayout.addWidget(self.comboFormatoPrecio)

        self.comboPeriodo = QComboBox(AjustesView)
        self.comboPeriodo.addItem("")
        self.comboPeriodo.addItem("")
        self.comboPeriodo.setObjectName(u"comboPeriodo")
        self.comboPeriodo.setStyleSheet(u"QComboBox {\n"
"    background-color: #0f3a43;\n"
"    color: #ecfeff;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 12px;\n"
"\n"
"    padding: 2px 8px;          /* \u2b05\ufe0f 1px menos */\n"
"    padding-right: 32px;\n"
"\n"
"    font-size: 12px;\n"
"    min-height: 34px;           /* \u2b05\ufe0f antes 38 */\n"
"}\n"
"\n"
"/* =========================================\n"
"   COMBOBOX \u2013 DESPLEGABLE AJUSTADO A ESTE TAMA\u00d1O\n"
"========================================= */\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: content;\n"
"    subcontrol-position: right center;\n"
"    width: 28px;\n"
"    border-left: 1px solid #1f6f7a;\n"
"}\n"
"\n"
"/* Quitamos la flecha por est\u00e9tica */\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"/* Lista desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #0b2a30;\n"
"    color: #cfe9ee;\n"
"\n"
"    border: 1px solid #155e75;\n"
"    border-radius: 8px;\n"
"\n"
"    max-height: 110px;          /* \ud83d"
                        "\udd11 CLAVE */\n"
"    padding: 2px;\n"
"\n"
"    selection-background-color: #22d3ee;\n"
"    selection-color: #041518;\n"
"\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Items */\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 2px 8px;           /* compacto */\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #155e6a;\n"
"    color: #ecfeff;\n"
"}\n"
"\n"
"/* Seleccionado */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #22d3ee;\n"
"    color: #041518;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    background-color: #155e6a;\n"
"    border: 1px solid #22d3ee;   /* MISMO GROSOR */\n"
"}")

        self.vboxLayout.addWidget(self.comboPeriodo)

        self.comboVista = QComboBox(AjustesView)
        self.comboVista.addItem("")
        self.comboVista.addItem("")
        self.comboVista.setObjectName(u"comboVista")
        self.comboVista.setStyleSheet(u"QComboBox {\n"
"    background-color: #0f3a43;\n"
"    color: #ecfeff;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 12px;\n"
"\n"
"    padding: 2px 8px;          /* \u2b05\ufe0f 1px menos */\n"
"    padding-right: 32px;\n"
"\n"
"    font-size: 12px;\n"
"    min-height: 34px;           /* \u2b05\ufe0f antes 38 */\n"
"}\n"
"\n"
"/* =========================================\n"
"   COMBOBOX \u2013 DESPLEGABLE AJUSTADO A ESTE TAMA\u00d1O\n"
"========================================= */\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: content;\n"
"    subcontrol-position: right center;\n"
"    width: 28px;\n"
"    border-left: 1px solid #1f6f7a;\n"
"}\n"
"\n"
"/* Quitamos la flecha por est\u00e9tica */\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"/* Lista desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #0b2a30;\n"
"    color: #cfe9ee;\n"
"\n"
"    border: 1px solid #155e75;\n"
"    border-radius: 8px;\n"
"\n"
"    max-height: 110px;          /* \ud83d"
                        "\udd11 CLAVE */\n"
"    padding: 2px;\n"
"\n"
"    selection-background-color: #22d3ee;\n"
"    selection-color: #041518;\n"
"\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Items */\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 2px 8px;           /* compacto */\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #155e6a;\n"
"    color: #ecfeff;\n"
"}\n"
"\n"
"/* Seleccionado */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #22d3ee;\n"
"    color: #041518;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    background-color: #155e6a;\n"
"    border: 1px solid #22d3ee;   /* MISMO GROSOR */\n"
"}")

        self.vboxLayout.addWidget(self.comboVista)

        self.spinAvisoKm = QSpinBox(AjustesView)
        self.spinAvisoKm.setObjectName(u"spinAvisoKm")
        self.spinAvisoKm.setStyleSheet(u"/* =========================================\n"
"   SPINBOX \u2013 AZUL PETR\u00d3LEO\n"
"========================================= */\n"
"\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"    background-color: #0f3a43;\n"
"    color: #ecfeff;\n"
"\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 12px;\n"
"\n"
"    padding-left: 14px;\n"
"    padding-right: 36px;   /* espacio botones */\n"
"\n"
"    font-size: 14px;\n"
"    min-height: 34px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QSpinBox:hover,\n"
"QDoubleSpinBox:hover {\n"
"    border-color: #22d3ee;\n"
"    background-color: #134852;\n"
"}\n"
"\n"
"/* Focus (MISMO GROSOR \u2192 NO DESCUADRA) */\n"
"QSpinBox:focus,\n"
"QDoubleSpinBox:focus {\n"
"    background-color: #155e6a;\n"
"    border: 1px solid #22d3ee;\n"
"}\n"
"\n"
"/* Texto interno */\n"
"QSpinBox QAbstractSpinBox,\n"
"QDoubleSpinBox QAbstractSpinBox {\n"
"    background: transparent;\n"
"    color: #ecfeff;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"/* =========================================\n"
""
                        "   SPINBOX \u2013 BOTONES COLOR DIFERENTE\n"
"========================================= */\n"
"\n"
"/* Botones (+ / -) */\n"
"QSpinBox::up-button,\n"
"QDoubleSpinBox::up-button,\n"
"QSpinBox::down-button,\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: content;\n"
"    width: 18px;\n"
"\n"
"    border-left: 1px solid #1f6f7a;\n"
"\n"
"    background-color: #0891b2;   /* cian intenso */\n"
"}\n"
"\n"
"/* Bot\u00f3n subir */\n"
"QSpinBox::up-button,\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-position: right top;\n"
"    border-top-right-radius: 12px;\n"
"}\n"
"\n"
"/* Bot\u00f3n bajar */\n"
"QSpinBox::down-button,\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-position: right bottom;\n"
"    border-bottom-right-radius: 12px;\n"
"}\n"
"\n"
"/* Hover botones */\n"
"QSpinBox::up-button:hover,\n"
"QDoubleSpinBox::up-button:hover,\n"
"QSpinBox::down-button:hover,\n"
"QDoubleSpinBox::down-button:hover {\n"
"    background-color: #22c55e;   /* verde suave */\n"
"}\n"
"\n"
"/* Click */\n"
"QSp"
                        "inBox::up-button:pressed,\n"
"QDoubleSpinBox::up-button:pressed,\n"
"QSpinBox::down-button:pressed,\n"
"QDoubleSpinBox::down-button:pressed {\n"
"    background-color: #16a34a;   /* verde m\u00e1s fuerte */\n"
"}\n"
"\n"
"/* Quitamos flechas */\n"
"QSpinBox::up-arrow,\n"
"QDoubleSpinBox::up-arrow,\n"
"QSpinBox::down-arrow,\n"
"QDoubleSpinBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"")
        self.spinAvisoKm.setMaximum(100000)

        self.vboxLayout.addWidget(self.spinAvisoKm)

        self.checkAvisoConsumo = QCheckBox(AjustesView)
        self.checkAvisoConsumo.setObjectName(u"checkAvisoConsumo")
        self.checkAvisoConsumo.setStyleSheet(u"/* =========================================\n"
"   CHECKBOX \u2013 ESTILO AZUL PETR\u00d3LEO\n"
"========================================= */\n"
"\n"
"QCheckBox {\n"
"    color: #ecfeff;\n"
"    font-size: 13px;\n"
"    spacing: 10px;           /* separaci\u00f3n texto-caja */\n"
"}\n"
"\n"
"/* Caja del checkbox */\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"\n"
"    background-color: #0f3a43;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QCheckBox::indicator:hover {\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* Marcado */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #22d3ee;\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* \u2714 check */\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #38bdf8;\n"
"}\n"
"\n"
"/* Desactivado */\n"
"QCheckBox::indicator:disabled {\n"
"    background-color: #062023;\n"
"    border-color: #0e3a40;\n"
"}\n"
"\n"
"/* Texto desactivado */\n"
"QCheckBox:disabled {\n"
""
                        "    color: #7dd3fc;\n"
"}\n"
"")

        self.vboxLayout.addWidget(self.checkAvisoConsumo)

        self.checkConfirmar = QCheckBox(AjustesView)
        self.checkConfirmar.setObjectName(u"checkConfirmar")
        self.checkConfirmar.setStyleSheet(u"/* =========================================\n"
"   CHECKBOX \u2013 ESTILO AZUL PETR\u00d3LEO\n"
"========================================= */\n"
"\n"
"QCheckBox {\n"
"    color: #ecfeff;\n"
"    font-size: 13px;\n"
"    spacing: 10px;           /* separaci\u00f3n texto-caja */\n"
"}\n"
"\n"
"/* Caja del checkbox */\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"\n"
"    background-color: #0f3a43;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QCheckBox::indicator:hover {\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* Marcado */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #22d3ee;\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* \u2714 check */\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #38bdf8;\n"
"}\n"
"\n"
"/* Desactivado */\n"
"QCheckBox::indicator:disabled {\n"
"    background-color: #062023;\n"
"    border-color: #0e3a40;\n"
"}\n"
"\n"
"/* Texto desactivado */\n"
"QCheckBox:disabled {\n"
""
                        "    color: #7dd3fc;\n"
"}\n"
"")

        self.vboxLayout.addWidget(self.checkConfirmar)

        self.checkCerrarSesion = QCheckBox(AjustesView)
        self.checkCerrarSesion.setObjectName(u"checkCerrarSesion")
        self.checkCerrarSesion.setStyleSheet(u"/* =========================================\n"
"   CHECKBOX \u2013 ESTILO AZUL PETR\u00d3LEO\n"
"========================================= */\n"
"\n"
"QCheckBox {\n"
"    color: #ecfeff;\n"
"    font-size: 13px;\n"
"    spacing: 10px;           /* separaci\u00f3n texto-caja */\n"
"}\n"
"\n"
"/* Caja del checkbox */\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"\n"
"    background-color: #0f3a43;\n"
"    border: 1px solid #1f6f7a;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QCheckBox::indicator:hover {\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* Marcado */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #22d3ee;\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* \u2714 check */\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #38bdf8;\n"
"}\n"
"\n"
"/* Desactivado */\n"
"QCheckBox::indicator:disabled {\n"
"    background-color: #062023;\n"
"    border-color: #0e3a40;\n"
"}\n"
"\n"
"/* Texto desactivado */\n"
"QCheckBox:disabled {\n"
""
                        "    color: #7dd3fc;\n"
"}\n"
"")

        self.vboxLayout.addWidget(self.checkCerrarSesion)

        self.hboxLayout = QHBoxLayout()
        self.hboxLayout.setObjectName(u"hboxLayout")
        self.btnGuardar = QPushButton(AjustesView)
        self.btnGuardar.setObjectName(u"btnGuardar")
        self.btnGuardar.setStyleSheet(u"/* =========================================\n"
"   BOT\u00d3N ALTERNATIVO \u2013 BLANCO AZULADO\n"
"========================================= */\n"
"\n"
"QPushButton {\n"
"    background-color: #f1f5f9;      /* blanco azulado suave */\n"
"    color: #0f3a43;                 /* azul petr\u00f3leo oscuro */\n"
"\n"
"    border: 1px solid #22d3ee;\n"
"    border-radius: 12px;\n"
"\n"
"    padding: 10px 18px;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* Hover */\n"
"QPushButton:hover {\n"
"    background-color: #e0f2fe;      /* azul muy claro */\n"
"    color: #0b2a30;\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* Presionado */\n"
"QPushButton:pressed {\n"
"    background-color: #bae6fd;\n"
"    border-color: #06b6d4;\n"
"}\n"
"\n"
"/* Desactivado */\n"
"QPushButton:disabled {\n"
"    background-color: #e5e7eb;\n"
"    color: #64748b;\n"
"    border-color: #94a3b8;\n"
"}\n"
"")

        self.hboxLayout.addWidget(self.btnGuardar)

        self.btnVolver = QPushButton(AjustesView)
        self.btnVolver.setObjectName(u"btnVolver")
        self.btnVolver.setStyleSheet(u"/* =========================================\n"
"   BOT\u00d3N ALTERNATIVO \u2013 BLANCO AZULADO\n"
"========================================= */\n"
"\n"
"QPushButton {\n"
"    background-color: #f1f5f9;      /* blanco azulado suave */\n"
"    color: #0f3a43;                 /* azul petr\u00f3leo oscuro */\n"
"\n"
"    border: 1px solid #22d3ee;\n"
"    border-radius: 12px;\n"
"\n"
"    padding: 10px 18px;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* Hover */\n"
"QPushButton:hover {\n"
"    background-color: #e0f2fe;      /* azul muy claro */\n"
"    color: #0b2a30;\n"
"    border-color: #22d3ee;\n"
"}\n"
"\n"
"/* Presionado */\n"
"QPushButton:pressed {\n"
"    background-color: #bae6fd;\n"
"    border-color: #06b6d4;\n"
"}\n"
"\n"
"/* Desactivado */\n"
"QPushButton:disabled {\n"
"    background-color: #e5e7eb;\n"
"    color: #64748b;\n"
"    border-color: #94a3b8;\n"
"}\n"
"")

        self.hboxLayout.addWidget(self.btnVolver)


        self.vboxLayout.addLayout(self.hboxLayout)


        self.retranslateUi(AjustesView)

        QMetaObject.connectSlotsByName(AjustesView)
    # setupUi

    def retranslateUi(self, AjustesView):
        AjustesView.setWindowTitle(QCoreApplication.translate("AjustesView", u"Ajustes", None))
        self.labelTitulo.setText(QCoreApplication.translate("AjustesView", u"Ajustes y preferencias", None))
        self.comboUnidadConsumo.setItemText(0, QCoreApplication.translate("AjustesView", u"L/100km", None))
        self.comboUnidadConsumo.setItemText(1, QCoreApplication.translate("AjustesView", u"km/L", None))

        self.comboFormatoPrecio.setItemText(0, QCoreApplication.translate("AjustesView", u"\u20ac", None))
        self.comboFormatoPrecio.setItemText(1, QCoreApplication.translate("AjustesView", u"$", None))

        self.comboPeriodo.setItemText(0, QCoreApplication.translate("AjustesView", u"Mensual", None))
        self.comboPeriodo.setItemText(1, QCoreApplication.translate("AjustesView", u"Anual", None))

        self.comboVista.setItemText(0, QCoreApplication.translate("AjustesView", u"lista", None))
        self.comboVista.setItemText(1, QCoreApplication.translate("AjustesView", u"grafica", None))

        self.checkAvisoConsumo.setText(QCoreApplication.translate("AjustesView", u"Avisar por consumo alto", None))
        self.checkConfirmar.setText(QCoreApplication.translate("AjustesView", u"Confirmar acciones importantes", None))
        self.checkCerrarSesion.setText(QCoreApplication.translate("AjustesView", u"Cerrar sesi\u00f3n al salir", None))
        self.btnGuardar.setText(QCoreApplication.translate("AjustesView", u"Guardar", None))
        self.btnVolver.setText(QCoreApplication.translate("AjustesView", u"Volver", None))
    # retranslateUi

